#!/usr/bin/env python
## Copyright 2011, Scott W. Dunlop <swdunlop@gmail.com> All rights reserved.
##
## AndBug is free software: you can redistribute it and/or modify it under 
## the terms of version 3 of the GNU Lesser General Public License as 
## published by the Free Software Foundation.
##
## AndBug is distributed in the hope that it will be useful, but WITHOUT ANY
## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
## FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for 
## more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with AndBug.  If not, see <http://www.gnu.org/licenses/>.

'this script executes command modules found in andbug.commands'

import andbug, sys, os, os.path
import andbug.cmd, andbug.command
from Queue import Queue, Empty
import threading, traceback

inv = os.path.basename(sys.argv[0]).lower()

if inv == "andbug":
    args = sys.argv[1:]
else:
    args = [inv] + sys.argv[1:]

if not args: args = ['help']
andbug.command.load_commands()

# this mess is to work around python's ctrl-c insanity
q = Queue()

def main():
    import atexit
    atexit.register(sys.stdout.write, '\x1B[0m\n')

    try:
        q.put(andbug.command.run_command(args))
    except andbug.command.UserError as err:
        print '!! %s' % err
        q.put(-1)
    except Exception as exc:
        traceback.print_exc()
        q.put(-1)

threading.Thread(target=main).start()
try:
    while True:
        try:
            ret = q.get(True, .01)
            if ret is not None: 
                sys.exit(ret)
        except Empty:
            pass # sigh
except KeyboardInterrupt:
    sys.exit(1)
