/* Generated by Pyrex 0.9.9 on Tue Jun  7 11:35:03 2011 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "wire.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[],     Py_ssize_t nargs, PyObject **args2, PyObject **kwds2, char rqd_kwds[]); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from jdwp */


/* Declarations from implementation of jdwp */

struct __pyx_obj_4jdwp_JdwpBuffer {
  PyObject_HEAD
  struct __pyx_vtabstruct_4jdwp_JdwpBuffer *__pyx_vtab;
  jdwp_buffer buf;
};


struct __pyx_vtabstruct_4jdwp_JdwpBuffer {
  PyObject *(*size)(struct __pyx_obj_4jdwp_JdwpBuffer *,PyObject *,PyObject *);
};
static struct __pyx_vtabstruct_4jdwp_JdwpBuffer *__pyx_vtabptr_4jdwp_JdwpBuffer;

static PyTypeObject *__pyx_ptype_4jdwp_JdwpBuffer = 0;
static PyObject *__pyx_f_4jdwp_einz(int); /*proto*/

static char __pyx_k1[] = "code";
static char __pyx_k2[] = "mesg";
static char __pyx_k3[] = "jdwp-error (%s): %s";
static char __pyx_k4[] = "JdwpError";
static char __pyx_k5[] = "";
static char __pyx_k6[] = "preparePack";
static char __pyx_k7[] = "packStr";
static char __pyx_k8[] = "prepareUnpack";
static char __pyx_k9[] = "unpackStr";
static char __pyx_k10[] = "jdwp";
static char __pyx_k11[] = "__init__";
static char __pyx_k12[] = "__str__";

static PyObject *__pyx_n_JdwpError;
static PyObject *__pyx_n___init__;
static PyObject *__pyx_n___str__;
static PyObject *__pyx_n_code;
static PyObject *__pyx_n_jdwp;
static PyObject *__pyx_n_mesg;
static PyObject *__pyx_n_packStr;
static PyObject *__pyx_n_preparePack;
static PyObject *__pyx_n_prepareUnpack;
static PyObject *__pyx_n_unpackStr;

static PyObject *__pyx_k3p;
static PyObject *__pyx_k5p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_JdwpError, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n___init__, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n___str__, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_code, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_jdwp, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_mesg, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_packStr, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_preparePack, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_prepareUnpack, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_unpackStr, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k3p, 0, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k5p, 0, __pyx_k5, sizeof(__pyx_k5)},
  {0, 0, 0, 0}
};

static PyObject *__pyx_d1;
static PyObject *__pyx_d2;
static PyObject *__pyx_d3;
static PyObject *__pyx_d4;
static PyObject *__pyx_d5;
static PyObject *__pyx_d6;
static PyObject *__pyx_d7;


/* Implementation of jdwp */

static PyObject *__pyx_f_4jdwp_9JdwpError___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_4jdwp_9JdwpError___init__ = {"__init__", (PyCFunction)__pyx_f_4jdwp_9JdwpError___init__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_4jdwp_9JdwpError___init__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_v_code = 0;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"self","code",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_self, &__pyx_v_code)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_code);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":69 */
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_code, __pyx_v_code) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":70 */
  __pyx_1 = PyInt_AsSsize_t(__pyx_v_code); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_2 = PyString_FromString((jdwp_en_errors[__pyx_1])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n_mesg, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("jdwp.JdwpError.__init__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_code);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_9JdwpError___str__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_4jdwp_9JdwpError___str__ = {"__str__", (PyCFunction)__pyx_f_4jdwp_9JdwpError___str__, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_f_4jdwp_9JdwpError___str__(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_self = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"self",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_self)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_code); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_mesg); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_1 = PyNumber_Remainder(__pyx_k3p, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("jdwp.JdwpError.__str__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_einz(int __pyx_v_code) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":77 */
  __pyx_1 = (__pyx_v_code == 0);
  if (__pyx_1) {
    __pyx_r = Py_None; Py_INCREF(Py_None);
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":78 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_JdwpError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_code); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __Pyx_Raise(__pyx_3, 0, 0);
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("jdwp.einz");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

static int __pyx_f_4jdwp_10JdwpBuffer___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_4jdwp_10JdwpBuffer___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":94 */
  ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.data = NULL;

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_4jdwp_10JdwpBuffer___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_4jdwp_10JdwpBuffer___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);
  jdwp_purge((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf));

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packU8(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packU8(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint8_t __pyx_v_byte;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"byte",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "B", __pyx_argnames, &__pyx_v_byte)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_u8((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_byte)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packU8");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packU16(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packU16(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint16_t __pyx_v_word;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"word",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "H", __pyx_argnames, &__pyx_v_word)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_u16((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_word)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packU16");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packU32(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packU32(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint32_t __pyx_v_quad;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"quad",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "I", __pyx_argnames, &__pyx_v_quad)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_u32((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_quad)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packU32");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packU64(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packU64(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_octet;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"octet",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "K", __pyx_argnames, &__pyx_v_octet)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_u64((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_octet)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packU64");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packInt(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packInt(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int32_t __pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"i",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_i)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_u32((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_i)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packInt");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packLong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packLong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int64_t __pyx_v_l;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"l",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "L", __pyx_argnames, &__pyx_v_l)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_u64((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_l)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packLong");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packObjectId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packObjectId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_id;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"id",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "K", __pyx_argnames, &__pyx_v_id)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_object_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_id)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packObjectId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packFieldId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packFieldId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_id;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"id",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "K", __pyx_argnames, &__pyx_v_id)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_field_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_id)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packFieldId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packMethodId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packMethodId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_id;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"id",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "K", __pyx_argnames, &__pyx_v_id)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_method_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_id)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packMethodId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packTypeId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packTypeId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_id;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"id",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "K", __pyx_argnames, &__pyx_v_id)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_type_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_id)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packTypeId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packFrameId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packFrameId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_id;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"id",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "K", __pyx_argnames, &__pyx_v_id)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_frame_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_id)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packFrameId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackU8(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackU8(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint8_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":125 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_u8((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":126 */
  __pyx_1 = PyInt_FromLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackU8");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackU16(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackU16(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint16_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":129 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_u16((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":130 */
  __pyx_1 = PyInt_FromLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackU16");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackU32(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackU32(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint32_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":133 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_u32((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":134 */
  __pyx_1 = PyLong_FromUnsignedLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackU32");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackU64(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackU64(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":137 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_u64((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":138 */
  __pyx_1 = PyLong_FromUnsignedLongLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackU64");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackInt(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackInt(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint32_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":141 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_u32((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":142 */
  __pyx_1 = PyInt_FromLong(((int32_t)__pyx_v_x)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackInt");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackFloat(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackFloat(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint32_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":145 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_u32((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":146 */
  __pyx_1 = PyFloat_FromDouble(((float)__pyx_v_x)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackFloat");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackDouble(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackDouble(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint32_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":149 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_u32((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":150 */
  __pyx_1 = PyFloat_FromDouble(((double)__pyx_v_x)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackDouble");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackLong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackLong(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":154 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_u64((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":155 */
  __pyx_1 = PyLong_FromLongLong(((int64_t)__pyx_v_x)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackLong");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackObjectId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackObjectId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":159 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_object_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 159; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":160 */
  __pyx_1 = PyLong_FromUnsignedLongLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackObjectId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackMethodId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackMethodId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":163 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_method_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":164 */
  __pyx_1 = PyLong_FromUnsignedLongLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackMethodId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackFrameId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackFrameId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":167 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_frame_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":168 */
  __pyx_1 = PyLong_FromUnsignedLongLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 168; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackFrameId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackFieldId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackFieldId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":171 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_field_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":172 */
  __pyx_1 = PyLong_FromUnsignedLongLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackFieldId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackTypeId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackTypeId(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint64_t __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":175 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_type_id((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_x))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":176 */
  __pyx_1 = PyLong_FromUnsignedLongLong(__pyx_v_x); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackTypeId");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackStr(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpackStr(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  uint32_t __pyx_v_sz;
  char *__pyx_v_str;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":181 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_unpack_str((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(&__pyx_v_sz),(&__pyx_v_str))); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 181; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":182 */
  __pyx_1 = PyString_FromStringAndSize(__pyx_v_str,__pyx_v_sz); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 182; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpackStr");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packStr(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_packStr(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_str = 0;
  char *__pyx_v_cstr;
  Py_ssize_t __pyx_v_sz;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"str",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_str)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_str);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":187 */
  __pyx_v_cstr = PyString_AsString(__pyx_v_str);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":188 */
  __pyx_v_sz = PyString_Size(__pyx_v_str);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":189 */
  __pyx_1 = __pyx_f_4jdwp_einz(jdwp_pack_str((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_sz,__pyx_v_cstr)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.packStr");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_str);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_config(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_config(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fSz = 0;
  PyObject *__pyx_v_mSz = 0;
  PyObject *__pyx_v_oSz = 0;
  PyObject *__pyx_v_tSz = 0;
  PyObject *__pyx_v_sSz = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  uint8_t __pyx_2;
  static char *__pyx_argnames[] = {"fSz","mSz","oSz","tSz","sSz",0};
  __pyx_v_fSz = __pyx_d1;
  __pyx_v_mSz = __pyx_d2;
  __pyx_v_oSz = __pyx_d3;
  __pyx_v_tSz = __pyx_d4;
  __pyx_v_sSz = __pyx_d5;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOOOO", __pyx_argnames, &__pyx_v_fSz, &__pyx_v_mSz, &__pyx_v_oSz, &__pyx_v_tSz, &__pyx_v_sSz)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fSz);
  Py_INCREF(__pyx_v_mSz);
  Py_INCREF(__pyx_v_oSz);
  Py_INCREF(__pyx_v_tSz);
  Py_INCREF(__pyx_v_sSz);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":193 */
  __pyx_1 = __pyx_v_fSz != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyInt_AsLong(__pyx_v_fSz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 193; goto __pyx_L1;}
    ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.fSz = __pyx_2;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":194 */
  __pyx_1 = __pyx_v_mSz != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyInt_AsLong(__pyx_v_mSz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
    ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.mSz = __pyx_2;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":195 */
  __pyx_1 = __pyx_v_oSz != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyInt_AsLong(__pyx_v_oSz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 195; goto __pyx_L1;}
    ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.oSz = __pyx_2;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":196 */
  __pyx_1 = __pyx_v_tSz != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyInt_AsLong(__pyx_v_tSz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
    ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.tSz = __pyx_2;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":197 */
  __pyx_1 = __pyx_v_sSz != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyInt_AsLong(__pyx_v_sSz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
    ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.sSz = __pyx_2;
    goto __pyx_L6;
  }
  __pyx_L6:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("jdwp.JdwpBuffer.config");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fSz);
  Py_DECREF(__pyx_v_mSz);
  Py_DECREF(__pyx_v_oSz);
  Py_DECREF(__pyx_v_tSz);
  Py_DECREF(__pyx_v_sSz);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_size(struct __pyx_obj_4jdwp_JdwpBuffer *__pyx_v_self,PyObject *__pyx_v_fmt,PyObject *__pyx_v_args) {
  int __pyx_v_i;
  int __pyx_v_sz;
  char __pyx_v_op;
  char *__pyx_v_cfmt;
  PyObject *__pyx_v_val;
  PyObject *__pyx_v_inc;
  PyObject *__pyx_r;
  char *__pyx_1;
  Py_ssize_t __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  Py_ssize_t __pyx_6;
  PyObject *__pyx_7 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fmt);
  Py_INCREF(__pyx_v_args);
  __pyx_v_val = Py_None; Py_INCREF(Py_None);
  __pyx_v_inc = Py_None; Py_INCREF(Py_None);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":204 */
  __pyx_1 = PyString_AsString(__pyx_v_fmt); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
  __pyx_v_cfmt = __pyx_1;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":206 */
  __pyx_v_sz = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":208 */
  __pyx_2 = PyObject_Length(__pyx_v_fmt); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_2; ++__pyx_v_i) {

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":209 */
    __pyx_3 = PyInt_FromLong(__pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_args, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_val);
    __pyx_v_val = __pyx_4;
    __pyx_4 = 0;

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":210 */
    __pyx_v_op = (__pyx_v_cfmt[__pyx_v_i]);

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":211 */
    __pyx_5 = (__pyx_v_op == '$');
    if (__pyx_5) {
      __pyx_6 = PyObject_Length(__pyx_v_val); if (__pyx_6 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 212; goto __pyx_L1;}
      __pyx_v_sz += (4 + __pyx_6);
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":214 */
      __pyx_3 = PyInt_FromLong(jdwp_size((&__pyx_v_self->buf),__pyx_v_op)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; goto __pyx_L1;}
      Py_DECREF(__pyx_v_inc);
      __pyx_v_inc = __pyx_3;
      __pyx_3 = 0;

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":215 */
      __pyx_4 = PyInt_FromLong(0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_v_inc, __pyx_4, &__pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; goto __pyx_L1;}
      __pyx_5 = __pyx_5 == 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      if (__pyx_5) {
        __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_JdwpError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
        __pyx_4 = PyInt_FromLong(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
        __pyx_7 = PyTuple_New(1); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_7, 0, __pyx_4);
        __pyx_4 = 0;
        __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_7); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        __Pyx_Raise(__pyx_4, 0, 0);
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
        goto __pyx_L5;
      }
      __pyx_L5:;

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":217 */
      __pyx_5 = PyInt_AsLong(__pyx_v_inc); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
      __pyx_v_sz += __pyx_5;
    }
    __pyx_L4:;
  }

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":219 */
  __pyx_3 = PyInt_FromLong(__pyx_v_sz); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 219; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.size");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_val);
  Py_DECREF(__pyx_v_inc);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fmt);
  Py_DECREF(__pyx_v_args);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_data(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_data(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_str;
  Py_ssize_t __pyx_v_len;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":225 */
  __pyx_v_str = ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.data;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":226 */
  __pyx_1 = (__pyx_v_str == NULL);
  if (__pyx_1) {
    Py_INCREF(__pyx_k5p);
    __pyx_r = __pyx_k5p;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":228 */
  __pyx_v_str = (__pyx_v_str + ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.ofs);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":229 */
  __pyx_v_len = ((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.len;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":230 */
  __pyx_2 = PyString_FromStringAndSize(__pyx_v_str,__pyx_v_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 230; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.data");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_preparePack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_preparePack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_sz = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"sz",0};
  __pyx_v_sz = __pyx_d6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_sz)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_sz);
  __pyx_1 = PyInt_AsLong(__pyx_v_sz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}
  jdwp_prepare((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),NULL,__pyx_1);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("jdwp.JdwpBuffer.preparePack");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_sz);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_prepareUnpack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_prepareUnpack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_str = 0;
  char *__pyx_v_cstr;
  Py_ssize_t __pyx_v_sz;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"str",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_str)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_str);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":239 */
  __pyx_v_cstr = PyString_AsString(__pyx_v_str);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":240 */
  __pyx_v_sz = PyString_Size(__pyx_v_str);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":241 */
  jdwp_prepare((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_cstr,__pyx_v_sz);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_str);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_pack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_pack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fmt = 0;
  PyObject *__pyx_v_args = 0;
  char *__pyx_v_cfmt;
  uint64_t __pyx_v_val;
  int __pyx_v_i;
  char __pyx_v_op;
  PyObject *__pyx_v_sz;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_ssize_t __pyx_4;
  int __pyx_5;
  uint64_t __pyx_6;
  static char *__pyx_argnames[] = {"fmt",0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 1, &__pyx_v_args, 0, 0) < 0) return 0;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_fmt)) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_args);
    return 0;
  }
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fmt);
  __pyx_v_sz = Py_None; Py_INCREF(Py_None);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":249 */
  __pyx_v_cfmt = PyString_AsString(__pyx_v_fmt);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":250 */
  __pyx_1 = PyString_FromString(__pyx_v_cfmt); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
  __pyx_2 = ((struct __pyx_vtabstruct_4jdwp_JdwpBuffer *)((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->__pyx_vtab)->size(((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self),__pyx_1,__pyx_v_args); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_sz);
  __pyx_v_sz = __pyx_2;
  __pyx_2 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":251 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_preparePack); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 251; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 251; goto __pyx_L1;}
  Py_INCREF(__pyx_v_sz);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_sz);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 251; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":252 */
  __pyx_4 = PyObject_Length(__pyx_v_fmt); if (__pyx_4 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_4; ++__pyx_v_i) {

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":253 */
    __pyx_v_op = (__pyx_v_cfmt[__pyx_v_i]);

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":254 */
    __pyx_5 = (__pyx_v_op == '$');
    if (__pyx_5) {
      __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_packStr); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
      __pyx_2 = PyInt_FromLong(__pyx_v_i); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
      __pyx_3 = PyObject_GetItem(__pyx_v_args, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
      __pyx_3 = 0;
      __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":257 */
      __pyx_1 = PyInt_FromLong(__pyx_v_i); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 257; goto __pyx_L1;}
      __pyx_2 = PyObject_GetItem(__pyx_v_args, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 257; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_6 = PyInt_AsUnsignedLongLongMask(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 257; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_v_val = __pyx_6;

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":258 */
      jdwp_pack((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_op,__pyx_v_val);
    }
    __pyx_L4:;
  }

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":260 */
  __pyx_4 = PyInt_AsSsize_t(__pyx_v_sz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 260; goto __pyx_L1;}
  __pyx_3 = PyString_FromStringAndSize(((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.data,__pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 260; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.pack");
  __pyx_r = 0;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_sz);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fmt);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_ipack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_ipack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fmt = 0;
  PyObject *__pyx_v_args = 0;
  char *__pyx_v_cfmt;
  uint64_t __pyx_v_val;
  int __pyx_v_i;
  char __pyx_v_op;
  PyObject *__pyx_v_sz;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  Py_ssize_t __pyx_4;
  PyObject *__pyx_5 = 0;
  uint64_t __pyx_6;
  static char *__pyx_argnames[] = {"fmt",0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 1, &__pyx_v_args, 0, 0) < 0) return 0;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_fmt)) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_args);
    return 0;
  }
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fmt);
  __pyx_v_sz = Py_None; Py_INCREF(Py_None);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":268 */
  __pyx_v_cfmt = PyString_AsString(__pyx_v_fmt);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":269 */
  __pyx_1 = PyString_FromString(__pyx_v_cfmt); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 269; goto __pyx_L1;}
  __pyx_2 = ((struct __pyx_vtabstruct_4jdwp_JdwpBuffer *)((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->__pyx_vtab)->size(((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self),__pyx_1,__pyx_v_args); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 269; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_sz);
  __pyx_v_sz = __pyx_2;
  __pyx_2 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":270 */
  __pyx_3 = PyInt_AsLong(__pyx_v_sz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
  jdwp_expand((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_3);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":271 */
  __pyx_4 = PyObject_Length(__pyx_v_fmt); if (__pyx_4 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 271; goto __pyx_L1;}
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_4; ++__pyx_v_i) {

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":272 */
    __pyx_v_op = (__pyx_v_cfmt[__pyx_v_i]);

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":273 */
    __pyx_3 = (__pyx_v_op == '$');
    if (__pyx_3) {
      __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_packStr); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
      __pyx_2 = PyInt_FromLong(__pyx_v_i); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
      __pyx_5 = PyObject_GetItem(__pyx_v_args, __pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_5);
      __pyx_5 = 0;
      __pyx_5 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":276 */
      __pyx_1 = PyInt_FromLong(__pyx_v_i); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 276; goto __pyx_L1;}
      __pyx_2 = PyObject_GetItem(__pyx_v_args, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 276; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_6 = PyInt_AsUnsignedLongLongMask(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 276; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_v_val = __pyx_6;

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":277 */
      jdwp_pack((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),__pyx_v_op,__pyx_v_val);
    }
    __pyx_L4:;
  }

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":279 */
  __pyx_4 = PyInt_AsSsize_t(__pyx_v_sz); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 279; goto __pyx_L1;}
  __pyx_5 = PyString_FromStringAndSize(((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf.data,__pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 279; goto __pyx_L1;}
  __pyx_r = __pyx_5;
  __pyx_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.ipack");
  __pyx_r = 0;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_sz);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fmt);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4jdwp_10JdwpBuffer_unpack(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fmt = 0;
  PyObject *__pyx_v_data = 0;
  char *__pyx_v_cfmt;
  uint64_t __pyx_v_v64;
  int __pyx_v_imax;
  int __pyx_v_i;
  char __pyx_v_op;
  PyObject *__pyx_v_val;
  PyObject *__pyx_v_vals;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_ssize_t __pyx_5;
  static char *__pyx_argnames[] = {"fmt","data",0};
  __pyx_v_data = __pyx_d7;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_fmt, &__pyx_v_data)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fmt);
  Py_INCREF(__pyx_v_data);
  __pyx_v_val = Py_None; Py_INCREF(Py_None);
  __pyx_v_vals = Py_None; Py_INCREF(Py_None);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":290 */
  __pyx_1 = __pyx_v_data != Py_None;
  if (__pyx_1) {
    __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_prepareUnpack); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L1;}
    Py_INCREF(__pyx_v_data);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_data);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":293 */
  __pyx_v_cfmt = PyString_AsString(__pyx_v_fmt);

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":294 */
  __pyx_2 = PyList_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 294; goto __pyx_L1;}
  Py_INCREF(Py_None);
  PyList_SET_ITEM(__pyx_2, 0, Py_None);
  __pyx_5 = PyObject_Length(__pyx_v_fmt); if (__pyx_5 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 294; goto __pyx_L1;}
  __pyx_3 = PyInt_FromSsize_t(__pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 294; goto __pyx_L1;}
  __pyx_4 = PyNumber_Multiply(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 294; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_vals);
  __pyx_v_vals = __pyx_4;
  __pyx_4 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":295 */
  __pyx_v_imax = PyInt_GetMax();

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":297 */
  __pyx_5 = PyObject_Length(__pyx_v_fmt); if (__pyx_5 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 297; goto __pyx_L1;}
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_5; ++__pyx_v_i) {

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":298 */
    __pyx_v_v64 = 0;

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":299 */
    __pyx_v_op = (__pyx_v_cfmt[__pyx_v_i]);

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":300 */
    __pyx_1 = (__pyx_v_op == '$');
    if (__pyx_1) {
      __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n_unpackStr); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 301; goto __pyx_L1;}
      __pyx_3 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 301; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_v_val);
      __pyx_v_val = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L5;
    }
    /*else*/ {

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":303 */
      jdwp_unpack((&((struct __pyx_obj_4jdwp_JdwpBuffer *)__pyx_v_self)->buf),(__pyx_v_cfmt[__pyx_v_i]),(&__pyx_v_v64));

      /* "/Code/AndBug/lib/jdwp/jdwp.pyx":305 */
      __pyx_1 = (__pyx_v_v64 > __pyx_v_imax);
      if (__pyx_1) {
        __pyx_4 = PyLong_FromLongLong(__pyx_v_v64); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
        Py_DECREF(__pyx_v_val);
        __pyx_v_val = __pyx_4;
        __pyx_4 = 0;
        goto __pyx_L6;
      }
      __pyx_1 = (__pyx_v_v64 < (-__pyx_v_imax));
      if (__pyx_1) {
        __pyx_2 = PyLong_FromLongLong(__pyx_v_v64); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
        Py_DECREF(__pyx_v_val);
        __pyx_v_val = __pyx_2;
        __pyx_2 = 0;
        goto __pyx_L6;
      }
      /*else*/ {
        __pyx_3 = PyInt_FromLong(__pyx_v_v64); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 310; goto __pyx_L1;}
        Py_DECREF(__pyx_v_val);
        __pyx_v_val = __pyx_3;
        __pyx_3 = 0;
      }
      __pyx_L6:;
    }
    __pyx_L5:;

    /* "/Code/AndBug/lib/jdwp/jdwp.pyx":312 */
    __pyx_4 = PyInt_FromLong(__pyx_v_i); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 312; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_vals, __pyx_4, __pyx_v_val) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 312; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
  }

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":314 */
  Py_INCREF(__pyx_v_vals);
  __pyx_r = __pyx_v_vals;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("jdwp.JdwpBuffer.unpack");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_val);
  Py_DECREF(__pyx_v_vals);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fmt);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}
static struct __pyx_vtabstruct_4jdwp_JdwpBuffer __pyx_vtable_4jdwp_JdwpBuffer;

static PyObject *__pyx_tp_new_4jdwp_JdwpBuffer(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_4jdwp_JdwpBuffer *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_4jdwp_JdwpBuffer *)o);
  *(struct __pyx_vtabstruct_4jdwp_JdwpBuffer **)&p->__pyx_vtab = __pyx_vtabptr_4jdwp_JdwpBuffer;
  if (__pyx_f_4jdwp_10JdwpBuffer___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_4jdwp_JdwpBuffer(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_4jdwp_10JdwpBuffer___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_4jdwp_JdwpBuffer[] = {
  {"packU8", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packU8, METH_VARARGS|METH_KEYWORDS, 0},
  {"packU16", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packU16, METH_VARARGS|METH_KEYWORDS, 0},
  {"packU32", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packU32, METH_VARARGS|METH_KEYWORDS, 0},
  {"packU64", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packU64, METH_VARARGS|METH_KEYWORDS, 0},
  {"packInt", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packInt, METH_VARARGS|METH_KEYWORDS, 0},
  {"packLong", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packLong, METH_VARARGS|METH_KEYWORDS, 0},
  {"packObjectId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packObjectId, METH_VARARGS|METH_KEYWORDS, 0},
  {"packFieldId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packFieldId, METH_VARARGS|METH_KEYWORDS, 0},
  {"packMethodId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packMethodId, METH_VARARGS|METH_KEYWORDS, 0},
  {"packTypeId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packTypeId, METH_VARARGS|METH_KEYWORDS, 0},
  {"packFrameId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packFrameId, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackU8", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackU8, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackU16", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackU16, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackU32", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackU32, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackU64", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackU64, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackInt", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackInt, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackFloat", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackFloat, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackDouble", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackDouble, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackLong", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackLong, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackObjectId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackObjectId, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackMethodId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackMethodId, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackFrameId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackFrameId, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackFieldId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackFieldId, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackTypeId", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackTypeId, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpackStr", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpackStr, METH_VARARGS|METH_KEYWORDS, 0},
  {"packStr", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_packStr, METH_VARARGS|METH_KEYWORDS, 0},
  {"config", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_config, METH_VARARGS|METH_KEYWORDS, 0},
  {"data", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_data, METH_VARARGS|METH_KEYWORDS, 0},
  {"preparePack", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_preparePack, METH_VARARGS|METH_KEYWORDS, 0},
  {"prepareUnpack", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_prepareUnpack, METH_VARARGS|METH_KEYWORDS, 0},
  {"pack", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_pack, METH_VARARGS|METH_KEYWORDS, 0},
  {"ipack", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_ipack, METH_VARARGS|METH_KEYWORDS, 0},
  {"unpack", (PyCFunction)__pyx_f_4jdwp_10JdwpBuffer_unpack, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_JdwpBuffer = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_JdwpBuffer = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_JdwpBuffer = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_JdwpBuffer = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_4jdwp_JdwpBuffer = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "jdwp.JdwpBuffer", /*tp_name*/
  sizeof(struct __pyx_obj_4jdwp_JdwpBuffer), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_4jdwp_JdwpBuffer, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_JdwpBuffer, /*tp_as_number*/
  &__pyx_tp_as_sequence_JdwpBuffer, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_JdwpBuffer, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_JdwpBuffer, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_4jdwp_JdwpBuffer, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_4jdwp_JdwpBuffer, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initjdwp(void); /*proto*/
PyMODINIT_FUNC initjdwp(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("jdwp", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;};
  __pyx_vtabptr_4jdwp_JdwpBuffer = &__pyx_vtable_4jdwp_JdwpBuffer;
  *(void(**)(void))&__pyx_vtable_4jdwp_JdwpBuffer.size = (void(*)(void))__pyx_f_4jdwp_10JdwpBuffer_size;
  if (PyType_Ready(&__pyx_type_4jdwp_JdwpBuffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_4jdwp_JdwpBuffer.tp_dict, __pyx_vtabptr_4jdwp_JdwpBuffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "JdwpBuffer", (PyObject *)&__pyx_type_4jdwp_JdwpBuffer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  __pyx_ptype_4jdwp_JdwpBuffer = &__pyx_type_4jdwp_JdwpBuffer;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":67 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  Py_INCREF(PyExc_Exception);
  PyTuple_SET_ITEM(__pyx_2, 0, PyExc_Exception);
  __pyx_3 = __Pyx_CreateClass(__pyx_2, __pyx_1, __pyx_n_JdwpError, "jdwp"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":68 */
  __pyx_2 = PyCFunction_NewEx(&__pyx_mdef_4jdwp_9JdwpError___init__, 0, __pyx_n_jdwp); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___init__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":72 */
  __pyx_2 = PyCFunction_NewEx(&__pyx_mdef_4jdwp_9JdwpError___str__, 0, __pyx_n_jdwp); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_4 = PyMethod_New(__pyx_2, 0, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (PyObject_SetAttr(__pyx_3, __pyx_n___str__, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_JdwpError, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":192 */
  Py_INCREF(Py_None);
  __pyx_d1 = Py_None;
  Py_INCREF(Py_None);
  __pyx_d2 = Py_None;
  Py_INCREF(Py_None);
  __pyx_d3 = Py_None;
  Py_INCREF(Py_None);
  __pyx_d4 = Py_None;
  Py_INCREF(Py_None);
  __pyx_d5 = Py_None;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":232 */
  __pyx_2 = PyInt_FromLong(1024); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 232; goto __pyx_L1;}
  __pyx_d6 = __pyx_2;
  __pyx_2 = 0;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":281 */
  Py_INCREF(Py_None);
  __pyx_d7 = Py_None;

  /* "/Code/AndBug/lib/jdwp/jdwp.pyx":356 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("jdwp");
}

static char *__pyx_filenames[] = {
  "jdwp.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    if (value == Py_None)
        value = NULL;
    if (tb == Py_None)
        tb = NULL;
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    if (tb && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_GetStarArgs(
    PyObject **args, 
    PyObject **kwds,
    char *kwd_list[], 
    Py_ssize_t nargs,
    PyObject **args2, 
    PyObject **kwds2,
    char rqd_kwds[])
{
    PyObject *x = 0, *args1 = 0, *kwds1 = 0;
    int i;
    char **p;
    
    if (args2)
        *args2 = 0;
    if (kwds2)
        *kwds2 = 0;
    
    if (args2) {
        args1 = PyTuple_GetSlice(*args, 0, nargs);
        if (!args1)
            goto bad;
        *args2 = PyTuple_GetSlice(*args, nargs, PyTuple_GET_SIZE(*args));
        if (!*args2)
            goto bad;
    }
    else if (PyTuple_GET_SIZE(*args) > nargs) {
        int m = nargs;
        int n = PyTuple_GET_SIZE(*args);
        PyErr_Format(PyExc_TypeError,
            "function takes at most %d positional arguments (%d given)",
                m, n);
        goto bad;
    }
    else {
        args1 = *args;
        Py_INCREF(args1);
    }
    
    if (rqd_kwds && !*kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i])
                    goto missing_kwarg;
    
    if (kwds2) {
        if (*kwds) {
            kwds1 = PyDict_New();
            if (!kwds1)
                goto bad;
            *kwds2 = PyDict_Copy(*kwds);
            if (!*kwds2)
                goto bad;
            for (i = 0, p = kwd_list; *p; i++, p++) {
                x = PyDict_GetItemString(*kwds, *p);
                if (x) {
                    if (PyDict_SetItemString(kwds1, *p, x) < 0)
                        goto bad;
                    if (PyDict_DelItemString(*kwds2, *p) < 0)
                        goto bad;
                }
                else if (rqd_kwds && rqd_kwds[i])
                    goto missing_kwarg;
            }
        }
        else {
            *kwds2 = PyDict_New();
            if (!*kwds2)
                goto bad;
        }
    }
    else {
        kwds1 = *kwds;
        Py_XINCREF(kwds1);
        if (rqd_kwds && *kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i] && !PyDict_GetItemString(*kwds, *p))
                        goto missing_kwarg;
    }
    
    *args = args1;
    *kwds = kwds1;
    return 0;
missing_kwarg:
    PyErr_Format(PyExc_TypeError,
        "required keyword argument '%s' is missing", *p);
bad:
    Py_XDECREF(args1);
    Py_XDECREF(kwds1);
    if (args2) {
        Py_XDECREF(*args2);
    }
    if (kwds2) {
        Py_XDECREF(*kwds2);
    }
    return -1;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

static PyObject *__Pyx_CreateClass(
    PyObject *bases, PyObject *dict, PyObject *name, char *modname)
{
    PyObject *py_modname;
    PyObject *result = 0;
    
    py_modname = PyString_FromString(modname);
    if (!py_modname)
        goto bad;
    if (PyDict_SetItemString(dict, "__module__", py_modname) < 0)
        goto bad;
    result = PyClass_New(bases, dict, name);
bad:
    Py_XDECREF(py_modname);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
